package generator

import "strings"

func (g *Generator) genQuerySelect(t *Table) {
	var fields []string
	var scanParams []string
	for _, c := range t.ColumnList {
		scanParams = append(scanParams, "&e."+c.GoName)
		fields = append(fields, c.DbName)
	}

	//查询单条纪录
	g.Pn("func (q *%sQuery)Select(ctx context.Context,tx *wrap.Tx) (e *%s,err error) {",
		t.GoName, t.GoName)
	g.Pn("    if !q.hasLimit{")
	g.Pn("        q.limitCount=1")
	g.Pn("        q.hasLimit=true")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    queryString,params:=q.buildSelectQuery()")
	g.Pn("    query:=bytes.NewBufferString(\"\")")
	g.Pn("    if len(q.getFields)==0{")
	g.Pn("        query.WriteString(\"SELECT %s FROM %s \")", strings.Join(fields, ","), t.DbName)
	g.Pn("    }else{")
	g.Pn("        query.WriteString(\"SELECT \")")
	g.Pn("        query.WriteString(strings.Join(q.getFields,\",\"))")
	g.Pn("        query.WriteString(\" FROM %s \")", t.DbName)
	g.Pn("    }")
	g.Pn("    query.WriteString(queryString)")
	g.Pn("    e=&%s{}", t.GoName)
	g.Pn("    row:=q.dao.db.QueryRow(ctx,tx,query.String(),params...)")
	g.Pn("    err=row.Scan(%s)", strings.Join(scanParams, ","))
	g.Pn("    if err==wrap.ErrNoRows{")
	g.Pn("        return nil,nil")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    return e,err")
	g.Pn("}")
	g.Pn("")

	//查询列表
	g.Pn("func (q *%sQuery)SelectList(ctx context.Context,tx *wrap.Tx) (list []*%s,err error) {",
		t.GoName, t.GoName)
	g.Pn("    queryString,params:=q.buildSelectQuery()")
	g.Pn("    query:=bytes.NewBufferString(\"\")")
	g.Pn("    if len(q.getFields)==0{")
	g.Pn("        query.WriteString(\"SELECT %s FROM %s \")", strings.Join(fields, ","), t.DbName)
	g.Pn("    }else{")
	g.Pn("        query.WriteString(\"SELECT \")")
	g.Pn("        query.WriteString(strings.Join(q.getFields,\",\"))")
	g.Pn("        query.WriteString(\" FROM %s \")", t.DbName)
	g.Pn("    }")
	g.Pn("    query.WriteString(queryString)")
	g.Pn("    rows,err:=q.dao.db.Query(ctx,tx,query.String(),params...)")
	g.Pn("    if err!=nil{")
	g.Pn("        return nil,err")
	g.Pn("    }")
	g.Pn("    for rows.Next(){")
	g.Pn("        e:=%s{}", t.GoName)
	g.Pn("        err=rows.Scan(%s)", strings.Join(scanParams, ","))
	g.Pn("        if err!=nil{")
	g.Pn("            return nil,err")
	g.Pn("        }")
	g.Pn("        list=append(list,&e)")
	g.Pn("    }")
	g.Pn("    if rows.Err()!=nil{")
	g.Pn("        err=rows.Err()")
	g.Pn("        return nil,err")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    return list,nil")
	g.Pn("}")
	g.Pn("")

	//查询数量
	g.Pn("func (q *%sQuery)SelectCount(ctx context.Context,tx *wrap.Tx) (count int64,err error) {",
		t.GoName)
	g.Pn("    queryString,params:=q.buildSelectQuery()")
	g.Pn("    query:=bytes.NewBufferString(\"\")")
	g.Pn("    query.WriteString(\"SELECT COUNT(*) FROM %s \")", t.DbName)
	g.Pn("    query.WriteString(queryString)")
	g.Pn("    row:=q.dao.db.QueryRow(ctx,tx,query.String(),params...)")
	g.Pn("    err=row.Scan(&count)")
	g.Pn("")
	g.Pn("    return count,err")
	g.Pn("}")
	g.Pn("")

	//分组查询
	g.Pn("func (q *%sQuery)SelectGroupBy(ctx context.Context,tx *wrap.Tx,withCount bool) "+
		"(rows *wrap.Rows,err error) {", t.GoName)
	g.Pn("    queryString,params:=q.buildSelectQuery()")
	g.Pn("    query:=bytes.NewBufferString(\"\")")
	g.Pn("    query.WriteString(\"SELECT \")")
	g.Pn("    query.WriteString(strings.Join(q.groupByFields,\",\"))")
	g.Pn("    if withCount{")
	g.Pn("        query.WriteString(\",Count(*) \")")
	g.Pn("    }")
	g.Pn("    query.WriteString(\" FROM %s \")", t.DbName)
	g.Pn("    query.WriteString(queryString)")
	g.Pn("")
	g.Pn("    return q.dao.db.Query(ctx,tx,query.String(),params...)")
	g.Pn("}")
	g.Pn("")

	//查询单条纪录（返回指定字段）
	g.Pn("func (q *%sQuery)SelectRow(ctx context.Context,tx *wrap.Tx) (row *wrap.Row) {", t.GoName)
	g.Pn("    if !q.hasLimit{")
	g.Pn("        q.limitCount=1")
	g.Pn("        q.hasLimit=true")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    queryString,params:=q.buildSelectQuery()")
	g.Pn("    query:=bytes.NewBufferString(\"\")")
	g.Pn("    query.WriteString(\"SELECT \")")
	g.Pn("    query.WriteString(strings.Join(q.getFields,\",\"))")
	g.Pn("    query.WriteString(\" FROM %s \")", t.DbName)
	g.Pn("    query.WriteString(queryString)")
	g.Pn("    return q.dao.db.QueryRow(ctx,tx,query.String(),params...)")
	g.Pn("}")
	g.Pn("")

	//查询多条纪录（返回指定字段）
	g.Pn("func (q *%sQuery)SelectRows(ctx context.Context,tx *wrap.Tx) (rows *wrap.Rows,err error) {", t.GoName)
	g.Pn("    queryString,params:=q.buildSelectQuery()")
	g.Pn("    query:=bytes.NewBufferString(\"\")")
	g.Pn("    query.WriteString(\"SELECT \")")
	g.Pn("    query.WriteString(strings.Join(q.getFields,\",\"))")
	g.Pn("    query.WriteString(\" FROM %s \")", t.DbName)
	g.Pn("    query.WriteString(queryString)")
	g.Pn("    return q.dao.db.Query(ctx,tx,query.String(),params...)")
	g.Pn("}")
	g.Pn("")
}
