package generator

func (g *Generator) genQueryUpdate(t *Table) {
	g.Pn("func (q *%sQuery)Update(ctx context.Context,tx *wrap.Tx)(result *wrap.Result,err error){", t.GoName)
	g.Pn("    query:=bytes.NewBufferString(\"\")")
	g.Pn("    var params []interface{}")
	g.Pn("    params=append(params,q.updateParams...)")
	g.Pn("    query.WriteString(\"UPDATE %s SET \")", t.DbName)
	g.Pn("    updateItems:=make([]string,len(q.updateFields))")
	g.Pn("    for i,v:=range q.updateFields{")
	g.Pn("        updateItems[i]=v+\"=?\"")
	g.Pn("    }")
	g.Pn("    query.WriteString(strings.Join(updateItems,\",\"))")
	g.Pn("    query.WriteString(\",update_time=now()\")")
	g.Pn("    where:=q.where.String()")
	g.Pn("    if where!=\"\"{")
	g.Pn("        query.WriteString(\" WHERE \")")
	g.Pn("        query.WriteString(where)")
	g.Pn("        params=append(params,q.whereParams...)")
	g.Pn("    }")
	g.Pn("    ")
	g.Pn("    return q.dao.db.Exec(ctx,tx,query.String(),params...)")
	g.Pn("}")
	g.Pn("")
}
