package generator

func (g *Generator) genCommonQuery() {
	// 查询基础定义
	g.Pn("type QueryBase struct {")
	g.Pn("    tableName string")
	g.Pn("    where *bytes.Buffer")
	g.Pn("    whereParams []interface{}")
	g.Pn("    groupByFields []string")
	g.Pn("    groupByOrders []bool")
	g.Pn("    orderByFields []string")
	g.Pn("    orderByOrders []bool")
	g.Pn("    hasLimit bool")
	g.Pn("    limitStartIncluded int64")
	g.Pn("    limitCount int64")
	g.Pn("    forUpdate bool")
	g.Pn("    forShare bool")
	g.Pn("    updateFields []string")
	g.Pn("    updateParams []interface{}")
	g.Pn("    getFields []string")
	g.Pn("    duplicatedUpdateFields []string")
	g.Pn("}")
	g.Pn("")

	// 构造查询语句及参数
	g.Pn("func (q *QueryBase)buildSelectQuery() (queryString string,params []interface{}) {")
	g.Pn("    query:=bytes.NewBufferString(\"\")")
	g.Pn("")
	g.Pn("    where:=q.where.String()")
	g.Pn("    if where!=\"\"{")
	g.Pn("        query.WriteString(\" WHERE \")")
	g.Pn("        query.WriteString(where)")
	g.Pn("        params=append(params,q.whereParams...)")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    groupByCount:=len(q.groupByFields)")
	g.Pn("    if groupByCount>0{")
	g.Pn("        groupByItems:=make([]string,groupByCount)")
	g.Pn("        for i,v:=range q.groupByFields{")
	g.Pn("            if q.groupByOrders[i]{")
	g.Pn("                groupByItems[i]=v+\" ASC\"")
	g.Pn("            }else{")
	g.Pn("                groupByItems[i]=v+\" DESC\"")
	g.Pn("            }")
	g.Pn("        }")
	g.Pn("        query.WriteString(\" GROUP BY \")")
	g.Pn("        query.WriteString(strings.Join(groupByItems,\",\"))")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    var orderByItems []string")
	g.Pn("    orderByCount:=len(q.orderByFields)")
	g.Pn("    if orderByCount>0{")
	g.Pn("        orderByItems=make([]string,orderByCount)")
	g.Pn("        for i,v:=range q.orderByFields{")
	g.Pn("            if q.orderByOrders[i]{")
	g.Pn("                orderByItems[i]=v+\" ASC\"")
	g.Pn("            }else{")
	g.Pn("                orderByItems[i]=v+\" DESC\"")
	g.Pn("            }")
	g.Pn("        }")
	g.Pn("        query.WriteString(\" ORDER BY \")")
	g.Pn("        query.WriteString(strings.Join(orderByItems,\",\"))")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    if q.hasLimit{")
	g.Pn("        query.WriteString(fmt.Sprintf(\" LIMIT %%d,%%d\",q.limitStartIncluded,q.limitCount))")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    if q.limitStartIncluded > 128 {") //limit优化
	g.Pn("        query=bytes.NewBufferString(fmt.Sprintf(\"INNER JOIN (SELECT id FROM %%s %%s) AS t USING(id)\"," +
		" q.tableName, query.String()))")
	g.Pn("        if len(orderByItems)>0{")
	g.Pn("            query.WriteString(\" ORDER BY \")")
	g.Pn("            query.WriteString(strings.Join(orderByItems,\",\"))")
	g.Pn("        }")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    if q.forUpdate{")
	g.Pn("        query.WriteString(\" FOR UPDATE\")")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    if q.forShare{")
	g.Pn("        query.WriteString(\" LOCK IN SHARE MODE\")")
	g.Pn("    }")
	g.Pn("")
	g.Pn("    return query.String(),params")
	g.Pn("}")
	g.Pn("")
}
